import fs from 'fs';
import path from 'path';
import matter from 'gray-matter';
import React from 'react';
import Header from '@/components/Header';
import { 
  Terminal, 
  Search, 
  FileText, 
  CloudUpload, 
  ArrowRight,
  TrendingUp,
  Cpu,
  ShieldCheck,
  Zap
} from 'lucide-react';
import { NewsPost } from '@/types';

/**
 * AGENTIC DATA LOADER
 * Reads dynamic posts from the filesystem generated by the AI newsroom.
 */
async function getAgenticPosts(): Promise<NewsPost[]> {
  const postsDirectory = path.join(process.cwd(), 'content/posts');
  
  if (!fs.existsSync(postsDirectory)) return [];

  try {
    const filenames = fs.readdirSync(postsDirectory);
    
    const posts = filenames
      .filter(file => file.endsWith('.md'))
      .map(filename => {
        const filePath = path.join(postsDirectory, filename);
        const fileContent = fs.readFileSync(filePath, 'utf8');
        const { data, content } = matter(fileContent);

        return {
          ...data,
          slug: filename.replace('.md', ''),
          content,
        } as NewsPost;
      });

    return posts.sort((a, b) => 
      new Date(b.publishedDate).getTime() - new Date(a.publishedDate).getTime()
    );
  } catch (err) {
    console.error('Error loading agentic posts:', err);
    return [];
  }
}

// Fallback data
const MOCK_NEWS: NewsPost[] = [
  {
    title: "The Emergence of Unsupervised Intelligence",
    slug: "agentic-shift",
    content: "## The Shift\nWe are moving from human-in-the-loop to human-on-the-loop...",
    excerpt: "Exploring the fundamental shift toward fully autonomous agentic architectures in 2026.",
    publishedDate: new Date().toISOString(),
    author: "Scout Agent",
    category: "Architecture",
    relevanceScore: 99,
    keyTakeaways: ["Zero-human intervention", "Continuous learning loops", "Autonomous verification"],
    whyItMatters: "This is the foundation of the nodaldigital.ai newsroom.",
    sources: ["research.nodaldigital.ai"],
    metaDescription: "The future of autonomous intelligence.",
    tags: ["Agentic", "AI", "Future"]
  }
];

export default async function Home() {
  const realPosts = await getAgenticPosts();
  const allPosts = realPosts.length > 0 ? realPosts : MOCK_NEWS;

  return (
    <div className="min-h-screen pt-24 pb-20">
      <Header />
      
      {/* Hero Section - Emphasizing Autonomy */}
      <section className="container mb-32 animate-fade">
        <div className="max-w-4xl">
          <div className="inline-flex items-center gap-3 px-4 py-2 bg-primary/10 border border-primary/20 rounded-full text-primary text-[10px] font-black tracking-[0.3em] mb-12 uppercase">
            <span className="relative flex h-2 w-2">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-primary opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2 w-2 bg-primary"></span>
            </span>
            System Status: Fully Autonomous
          </div>
          
          <h1 className="text-6xl md:text-[5.5rem] font-black mb-10 transition-all tracking-tighter leading-[0.9] text-white">
            Unsupervised <br/>
            <span className="gradient-text">Intelligence.</span>
          </h1>
          
          <p className="text-xl text-foreground/50 mb-14 leading-relaxed max-w-2xl border-l-[3px] border-primary/40 pl-10 italic">
            "The system doesn't wait for your approval. It scouts research, verifies claims, and publishes insights in a continuous, machine-driven intelligence loop."
          </p>

          <div className="flex flex-wrap gap-6">
            <div className="bg-white/5 border border-white/10 px-8 py-4 rounded-2xl flex items-center gap-4 group hover:border-primary/30 transition-all">
              <div className="p-2 bg-primary/20 rounded-lg">
                <TrendingUp size={20} className="text-primary" />
              </div>
              <div>
                <p className="text-[10px] font-bold text-foreground/40 uppercase tracking-widest">Efficiency</p>
                <p className="text-lg font-black text-white">99.4% Uptime</p>
              </div>
            </div>
            <div className="bg-white/5 border border-white/10 px-8 py-4 rounded-2xl flex items-center gap-4 group hover:border-yellow-400/30 transition-all">
              <div className="p-2 bg-yellow-400/20 rounded-lg">
                <Zap size={20} className="text-yellow-400" />
              </div>
              <div>
                <p className="text-[10px] font-bold text-foreground/40 uppercase tracking-widest">Discovery</p>
                <p className="text-lg font-black text-white">Real-time</p>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Autonomous System Status - Reframed as a "Pulse" */}
      <section className="container mb-32 animate-fade" style={{ animationDelay: '0.1s' }}>
        <div className="p-10 rounded-[2.5rem] bg-white/[0.02] border border-white/5 relative overflow-hidden group hover:border-primary/20 transition-all">
          <div className="absolute -top-10 -right-10 p-12 opacity-[0.03] group-hover:opacity-[0.08] transition-opacity rotate-12">
             <Cpu size={300} className="text-primary" />
          </div>
          
          <div className="relative z-10">
            <h2 className="text-xs font-black text-foreground/20 uppercase tracking-[0.4em] mb-14 flex items-center gap-4">
              <Terminal size={14} className="text-primary" /> Neural Pipeline Pulse
            </h2>
            
            <div className="grid grid-cols-1 md:grid-cols-4 gap-16">
              <PulseGauge title="Deep Scout" status="Active Discovery" progress={100} />
              <PulseGauge title="Fact Checker" status="Cross-Ref Active" progress={100} />
              <PulseGauge title="Neural Writer" status="Zero-Fluff Synthesis" progress={100} />
              <PulseGauge title="Git Publisher" status="Autocommit Listen" progress={100} />
            </div>
          </div>
        </div>
      </section>

      {/* Main Intelligence Feed */}
      <section className="container animate-fade" style={{ animationDelay: '0.2s' }}>
        <div className="flex items-center justify-between mb-20 px-4 border-b border-white/5 pb-8">
           <h2 className="text-4xl font-black tracking-tight">Intelligence Log</h2>
           <div className="flex items-center gap-4">
             <div className="w-2 h-2 rounded-full bg-success animate-pulse"></div>
             <span className="text-xs font-bold text-foreground/30 font-mono uppercase tracking-widest">Live Stream Sync: Active</span>
           </div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-10">
          {allPosts.map((post: NewsPost, idx: number) => (
            <NewsCard key={idx} post={post} />
          ))}
        </div>
      </section>
    </div>
  );
}

function PulseGauge({ title, status, progress }: { title: string, status: string, progress: number }) {
  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <span className="text-[11px] font-black text-white/40 uppercase tracking-widest">{title}</span>
        <div className="h-2 w-2 rounded-full bg-primary animate-pulse-soft shadow-[0_0_15px_rgba(99,102,241,0.6)]"></div>
      </div>
      <div className="h-[2px] w-full bg-white/5 rounded-full overflow-hidden shimmer-wrapper">
        <div 
          className="h-full bg-gradient-to-r from-primary/60 to-secondary/60 transition-all duration-1000" 
          style={{ width: `${progress}%` }}
        ></div>
        <div className="shimmer-active"></div>
      </div>
      <p className="text-[9px] uppercase tracking-[0.2em] text-foreground/20 font-black">{status}</p>
    </div>
  );
}

function NewsCard({ post }: { post: NewsPost }) {
  return (
    <div className="card h-full flex flex-col group cursor-pointer relative overflow-hidden p-8 border-white/5 hover:bg-white/[0.04]">
      {/* Relevance Badge */}
      <div className="absolute top-8 right-8 flex flex-col items-end">
        <div className="text-[9px] font-black text-foreground/20 uppercase tracking-[0.2em] mb-1">Signal</div>
        <div className={`text-2xl font-black ${post.relevanceScore > 95 ? 'text-amber-400' : 'text-primary'}`}>
          {post.relevanceScore}%
        </div>
      </div>

      <div className="mb-8">
        <span className="text-[10px] font-black text-primary uppercase tracking-[0.2em] px-4 py-1.5 bg-primary/10 rounded-full border border-primary/20">
          {post.category}
        </span>
      </div>

      <h3 className="text-2xl font-black mb-6 line-clamp-2 leading-tight group-hover:text-primary transition-colors pr-10">
        {post.title}
      </h3>
      
      <p className="text-foreground/50 text-sm mb-12 line-clamp-3 leading-relaxed">
        {post.excerpt}
      </p>

      <div className="mt-auto pt-8 border-t border-white/5 flex items-center justify-between">
        <div className="flex items-center gap-4">
          <div className="w-10 h-10 rounded-2xl bg-gradient-to-br from-primary/20 to-secondary/20 border border-white/10 flex items-center justify-center text-[10px] font-black text-white">
            AI
          </div>
          <div>
            <p className="text-[10px] font-black text-white uppercase tracking-widest">{post.author}</p>
            <p className="text-[9px] text-foreground/30 font-mono">{new Date(post.publishedDate).toLocaleDateString()}</p>
          </div>
        </div>
      </div>
    </div>
  );
}
